#!/bin/bash

set -e

SANDBOX=$(mktemp -d)

printf "Building Linux...\n"
GOOS=linux  GOARCH=amd64 go build -o $SANDBOX/copy-autoscaler-linux .

printf "Building OSX...\n"
GOOS=darwin  GOARCH=amd64 go build -o $SANDBOX/copy-autoscaler-darwin .

printf "Building Windows...\n"
GOOS=windows  GOARCH=amd64 go build -o $SANDBOX/copy-autoscaler.exe .

printf "\nBuild summary:\n"
find $SANDBOX -type f -exec file {} \;

printf "\nSHA-1 digests for CF cli plugin repo:\n"
shasum $SANDBOX/copy-autoscaler*

printf "\nBinaries are located here:\n$SANDBOX\n"
open $SANDBOX